import type { DataRecord, TicketRecord, UserRecord } from '@/types';

export const orgData: DataRecord[] = [
  {
    key: '1',
    organization: 'CBRE',
    owner: 'Morgan Bianchi',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'Rejected',
    creationDate: 'Jan 24, 2020',
  },
  {
    key: '2',
    organization: 'CBRE',
    owner: 'Jamie Nilsson',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'In Negotiation',
    creationDate: 'Jan 19, 2020',
  },
  {
    key: '3',
    organization: 'Google',
    owner: 'Sasha Schmidt',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'Under Review',
    creationDate: 'Jan 19, 2020',
  },
  {
    key: '4',
    organization: 'CW',
    owner: 'Alexei Varga',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'Accepted',
    creationDate: 'Jan 19, 2020',
  },
  {
    key: '5',
    organization: 'OWP',
    owner: 'Adrian Martinez',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'Accepted',
    creationDate: 'Jan 20, 2020',
  },
  {
    key: '6',
    organization: 'CW',
    owner: 'Alex Novak',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'Prospective',
    creationDate: 'Jan 24, 2020',
  },
  {
    key: '7',
    organization: 'Google',
    owner: 'Casey Wagner',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'In Negotiation',
    creationDate: 'Jan 20, 2020',
  },
  {
    key: '8',
    organization: 'CW',
    owner: 'Casey Wagner',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'Rejected',
    creationDate: 'Jan 20, 2020',
  },
  {
    key: '9',
    organization: 'OWP',
    owner: 'Alex Reyes',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'Accepted',
    creationDate: 'Jan 19, 2020',
  },
  {
    key: '10',
    organization: 'CBRE',
    owner: 'Jordan Kovacs',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'Prospective',
    creationDate: 'Feb 1, 2020',
  },
];

export const usersData: UserRecord[] = [
  {
    key: '1',
    id: '54.231.232.197',
    name: 'Ahmed',
    email: 'AhmedAhmed@gmail.com',
    role: 'Admin',
    status: true,
    lastLogin: 'Aug 25, 2025',
    creationDate: 'Jan 15, 2024',
  },
  {
    key: '2',
    id: '192.168.1.45',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    role: 'Viewer',
    status: true,
    lastLogin: 'Aug 24, 2025',
    creationDate: 'Mar 10, 2024',
  },
  {
    key: '3',
    id: '10.0.0.123',
    name: 'Marcus Chen',
    email: 'marcus.chen@company.com',
    role: 'Member',
    status: false,
    lastLogin: 'Aug 20, 2025',
    creationDate: 'Feb 28, 2024',
  },
  {
    key: '4',
    id: '172.16.254.1',
    name: 'Elena Rodriguez',
    email: 'elena.rodriguez@company.com',
    role: 'Admin',
    status: true,
    lastLogin: 'Aug 26, 2025',
    creationDate: 'Jan 5, 2024',
  },
  {
    key: '5',
    id: '203.0.113.42',
    name: 'David Kim',
    email: 'david.kim@company.com',
    role: 'Viewer',
    status: false,
    lastLogin: 'Never',
    creationDate: 'Aug 23, 2025',
  },
  {
    key: '6',
    id: '198.51.100.88',
    name: 'Lisa Thompson',
    email: 'lisa.thompson@company.com',
    role: 'Member',
    status: false,
    lastLogin: 'Aug 15, 2025',
    creationDate: 'Dec 12, 2023',
  },
  {
    key: '7',
    id: '192.0.2.146',
    name: 'Michael Brown',
    email: 'michael.brown@company.com',
    role: 'Owner',
    status: true,
    lastLogin: 'Aug 25, 2025',
    creationDate: 'May 18, 2024',
  },
  {
    key: '8',
    id: '10.1.1.200',
    name: 'Anna Kowalski',
    email: 'anna.kowalski@company.com',
    role: 'Admin',
    status: false,
    lastLogin: 'Aug 18, 2025',
    creationDate: 'Apr 7, 2024',
  },
  {
    key: '9',
    id: '172.31.0.55',
    name: 'James Wilson',
    email: 'james.wilson@company.com',
    role: 'Member',
    status: true,
    lastLogin: 'Aug 26, 2025',
    creationDate: 'Jun 22, 2024',
  },
  {
    key: '10',
    id: '192.168.100.77',
    name: 'Priya Patel',
    email: 'priya.patel@company.com',
    role: 'Admin',
    status: true,
    lastLogin: 'Aug 24, 2025',
    creationDate: 'Jul 14, 2024',
  },
];

export const ticketsData: TicketRecord[] = [
  {
    key: '1',
    ticketTitle: 'Ticket Title',
    description:
      "Description written describes the ticket issue, Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    priority: 'High',
    status: 'Pending',
    creationDate: 'Jan 15, 2024',
    updated: 'Aug 25, 2025',
  },
  {
    key: '2',
    ticketTitle: 'Ticket Title',
    description:
      "Description written describes the ticket issue, Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    priority: 'Medium',
    status: 'Pending',
    creationDate: 'Jan 15, 2024',
    updated: 'Aug 25, 2025',
  },
  {
    key: '3',
    ticketTitle: 'Ticket Title',
    description:
      "Description written describes the ticket issue, Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    priority: 'Medium',
    status: 'Pending',
    creationDate: 'Jan 15, 2024',
    updated: 'Aug 25, 2025',
  },
  {
    key: '4',
    ticketTitle: 'Ticket Title',
    description:
      "Description written describes the ticket issue, Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    priority: 'Medium',
    status: 'Pending',
    creationDate: 'Jan 15, 2024',
    updated: 'Aug 25, 2025',
  },
  {
    key: '5',
    ticketTitle: 'Ticket Title',
    description:
      "Description written describes the ticket issue, Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    priority: 'Low',
    status: 'Pending',
    creationDate: 'Jan 15, 2024',
    updated: 'Aug 25, 2025',
  },
  {
    key: '6',
    ticketTitle: 'Ticket Title',
    description:
      "Description written describes the ticket issue, Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    priority: 'Medium',
    status: 'Pending',
    creationDate: 'Jan 15, 2024',
    updated: 'Aug 25, 2025',
  },
  {
    key: '7',
    ticketTitle: 'Ticket Title',
    description:
      "Description written describes the ticket issue, Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    priority: 'High',
    status: 'Pending',
    creationDate: 'Jan 15, 2024',
    updated: 'Aug 25, 2025',
  },
  {
    key: '8',
    ticketTitle: 'Ticket Title',
    description:
      "Description written describes the ticket issue, Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    priority: 'High',
    status: 'Pending',
    creationDate: 'Jan 15, 2024',
    updated: 'Aug 25, 2025',
  },
  {
    key: '9',
    ticketTitle: 'Ticket Title',
    description:
      "Description written describes the ticket issue, Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    priority: 'High',
    status: 'Pending',
    creationDate: 'Jan 15, 2024',
    updated: 'Aug 25, 2025',
  },
  {
    key: '10',
    ticketTitle: 'Ticket Title',
    description:
      "Description written describes the ticket issue, Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    priority: 'High',
    status: 'Pending',
    creationDate: 'Jan 15, 2024',
    updated: 'Aug 25, 2025',
  },
];
