import type { DataRecord } from "@/types";

export const orgData: DataRecord[] = [
  {
    key: '1',
    organization: 'CBRE',
    owner: 'Morgan Bianchi',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'Rejected',
    creationDate: 'Jan 24, 2020',
  },
  {
    key: '2',
    organization: 'CBRE',
    owner: 'Jamie Nilsson',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'In Negotiation',
    creationDate: 'Jan 19, 2020',
  },
  {
    key: '3',
    organization: 'Google',
    owner: 'Sasha Schmidt',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'Under Review',
    creationDate: 'Jan 19, 2020',
  },
  {
    key: '4',
    organization: 'CW',
    owner: 'Alexei Varga',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'Accepted',
    creationDate: 'Jan 19, 2020',
  },
  {
    key: '5',
    organization: 'OWP',
    owner: 'Adrian Martinez',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'Accepted',
    creationDate: 'Jan 20, 2020',
  },
  {
    key: '6',
    organization: 'CW',
    owner: 'Alex Novak',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'Prospective',
    creationDate: 'Jan 24, 2020',
  },
  {
    key: '7',
    organization: 'Google',
    owner: 'Casey Wagner',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'In Negotiation',
    creationDate: 'Jan 20, 2020',
  },
  {
    key: '8',
    organization: 'CW',
    owner: 'Casey Wagner',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'Rejected',
    creationDate: 'Jan 20, 2020',
  },
  {
    key: '9',
    organization: 'OWP',
    owner: 'Alex Reyes',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'Accepted',
    creationDate: 'Jan 19, 2020',
  },
  {
    key: '10',
    organization: 'CBRE',
    owner: 'Jordan Kovacs',
    products: ['DWM', 'CTI', 'DRP'],
    status: 'Prospective',
    creationDate: 'Feb 1, 2020',
  },
];